let state;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function action(payload){const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){document.querySelector('#error').textContent=d.error;return null}state=d;document.querySelector('#error').textContent='';render();return d}
function render(){
 document.querySelector('#remaining').textContent=state.remaining_budget;document.querySelector('#method').value=state.method;
 document.querySelector('#summary').textContent=`${state.project}: ${state.work.length} distinct deliverables. ${state.spent} additional answers received. You can narrow any answer or leave work deferred.`;
 document.querySelector('#next').disabled=!!state.question||!state.remaining_budget;document.querySelector('#finish').disabled=!!state.question;
 const q=state.question;
 document.querySelector('#question').innerHTML=q?`<article class="card question"><span class="badge">${esc(q.label)}</span><h2>${esc(q.text)}</h2><p class="scope">Applies to: ${esc(q.scope)} · One answer unit</p><div class="enables"><b>Work this answer may enable</b><p>${q.enables.map(esc).join(', ')}</p></div>${q.additional_needed.some(x=>x.decisions.length)?`<p class="warning">A second answer may still be needed. ${q.additional_needed.filter(x=>x.decisions.length).map(x=>esc(x.task)+': '+x.decisions.map(esc).join(', ')).join('. ')}</p>`:''}<details data-inspect="question_source"><summary>Inspect the source and proposed scope</summary><p>${esc(q.source)}</p><p>Record version ${q.version}. Exceptions: ${q.exceptions.length?q.exceptions.map(esc).join(', '):'none recorded'}. No answer will be shared outside registered work.</p></details><form id="answer-form"><div class="form-row"><label>Your answer<input name="value" required placeholder="${q.kind==='scope'?'yes or no':'Your actual requirement'}"></label><label>Where it applies<select name="only_task"><option value="">${esc(q.scope)}</option>${q.kind==='scope'?'':q.enables.map(t=>`<option value="${esc(t)}">Only ${esc(t)}</option>`).join('')}</select></label></div><div class="buttons"><button class="primary">Use this answer</button><button type="button" id="defer">I cannot resolve this now</button></div></form></article>`:`<article class="card"><h3>${state.stop_reason?'The planner recommends stopping':state.remaining_budget?'Choose what to clarify next':'The answer budget is used'}</h3><p class="muted">${state.stop_reason?esc(state.stop_reason):state.remaining_budget?'The planner can recommend a question or stop if asking has no predicted benefit. You remain free to revise an instruction below.':'Remaining work stays visible. Finish with current answers, or start a new comparison with a different budget.'}</p></article>`;
 document.querySelector('#work').innerHTML=state.work.map(w=>`<article class="card ${w.status.startsWith('Ready')?'ready':'deferred'}"><h3>${esc(w.id)}</h3><span class="badge">${esc(w.status)}</span>${w.registered_release?`<p class="scope">Release: ${esc(w.registered_release.replaceAll('_',' '))}</p>`:''}${Object.keys(w.preview).length?`<details data-inspect="${esc(w.id)}"><summary>Inspect the current draft inputs</summary><pre>${esc(JSON.stringify(w.preview,null,2))}</pre></details>`:''}</article>`).join('');
 document.querySelector('#records').innerHTML=state.records.map(r=>`<div class="record"><div class="head"><b>${esc(r.label)}</b><span>${esc(r.value??'Unresolved')}</span></div><p class="scope">${esc(r.scope)} · ${esc(r.status)} · version ${r.version}</p><details data-inspect="${esc(r.id)}"><summary>Inspect, revise or make an exception</summary><button data-ask="${esc(r.id)}">Ask about this instead</button><p>${esc(r.source)}</p><p>Registered work: ${r.affected.map(esc).join(', ')}</p><form data-revise="${esc(r.id)}"><label>New instruction<input name="value" value="${esc(r.value??'')}"></label><label>Except these deliverables (exact names, comma separated)<input name="exceptions" value="${esc(r.exceptions.join(', '))}"></label><div class="buttons"><button>Revise and show affected work</button><button type="button" data-revoke="${esc(r.id)}">Revoke</button></div></form></details></div>`).join('');
 document.querySelector('#events').innerHTML=state.events.slice(-8).reverse().map(e=>`<div class="event"><b>${esc(e.kind.replaceAll('_',' '))}</b> ${esc(e.question?.text||e.id||e.task||'')}${e.affected?.length?' · Revalidate '+e.affected.map(esc).join(', '):''}</div>`).join('')||'<p class="muted">No questions have been answered in this demonstration.</p>';
 if(q){document.querySelector('#answer-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));action({action:'answer',...data})};document.querySelector('#defer').onclick=()=>action({action:'defer'})}
 document.querySelectorAll('[data-revise]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const x=Object.fromEntries(new FormData(f));action({action:'revise',id:f.dataset.revise,value:x.value,exceptions:x.exceptions.split(',').map(x=>x.trim()).filter(Boolean)})});
 document.querySelectorAll('[data-ask]').forEach(b=>b.onclick=()=>action({action:'ask',id:b.dataset.ask}));
 document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>action({action:'revise',id:b.dataset.revoke,revoke:true}));
 document.querySelectorAll('[data-inspect]').forEach(d=>d.ontoggle=()=>{if(d.open)fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'inspect',view:d.dataset.inspect})})});
}
document.querySelector('#next').onclick=()=>action({action:'next'});document.querySelector('#finish').onclick=()=>action({action:'finish'});document.querySelector('#reset').onclick=()=>action({action:'reset',method:document.querySelector('#method').value,budget:Number(document.querySelector('#budget').value)});fetch('/api/state').then(r=>r.json()).then(s=>{state=s;render()});
