"""Readable report and manuscript tables generated from saved evidence."""
from pathlib import Path
from .common import ART,ROOT,read,write
from .plot import NAMES

def build():
 a=read(ART/'analysis/summary.json');follow=read(ART/'parser_followup/analysis/summary.json');ledger=read(ART/'resource_ledger.json');comps=read(ART/'analysis/comparisons.json');fcomps=read(ART/'parser_followup/comparisons.json');variation=read(ART/'analysis/request_variation.json');terminal=read(ART/'analysis/terminal_envelope_audit.json');route=read(ART/'parser_followup/analysis/routing_audit.json')
 primary={r['method']:r for r in a['primary']};fs={r['method']:r for r in follow}
 def table(rs):
  lines=['| Method | Complete structured projects | Correct accepted artifacts | Unfinished | Accepted wrong | LLM calls | Tokens |','|---|---:|---:|---:|---:|---:|---:|']
  for r in rs:lines.append('| '+NAMES[r['method']]+' | '+str(r['project_correct_total'])+'/'+str(r['runs'])+' | '+str(r['accepted_correct_total'])+' | '+str(r['unfinished_total'])+' | '+str(r['accepted_wrong_total'])+' | '+str(r['calls_total'])+' | '+format(r['tokens_total'],',')+' |')
  return '\n'.join(lines)
 report=f'''# Coordinated adaptation on recorded retail transactions

## Conclusion

The prototype supports one scoped requirement change followed by verified updates to a connected analysis table, chart and numerical report while preserving an appendix. The real-data experiment supports this **engineering protocol**, but not a distinctive recipient-selection advance over a competent global check. A preventable tool-envelope parsing problem confounded the initial quality comparison. A separately declared, fresh-generation follow-up makes that limitation visible instead of replacing the original result.

With compatible parsing, targeted and same-packet global checking each completed **16/16 structured projects in 46 calls**, with identical request sequences on all sixteen pairs. Active broadcast completed 16/16 in 64 calls. The deterministic pipeline completed every original project in zero model calls. For these fully specified reporting contracts, use the simpler parameterized pipeline or normalized global check. More elaborate routing is not justified by this evidence.

These conclusions concern executable numerical contracts, not all generated prose. A generated report called stock codes customers despite passing the numerical guard. The default interface displays checked numerical claims and explicit contract labels; raw prose remains inspectable and unvalidated.

## Starting point, source and construction

Work began on `main` at `ecebc3749308a848c712b9cb22c8486269b10b3f` with a clean tree. Historical decision-dependency, clarification-planning and verification-escalation findings were read and preserved. No existing submission source was replaced. The new namespace is `research/coordination_injections/` and `artifacts/coordination_injections/`.

The primary source is [UCI Online Retail](https://archive.ics.uci.edu/dataset/352/online%2Bretail), Chen (2015), DOI [10.24432/C5BW33](https://doi.org/10.24432/C5BW33), CC BY 4.0. All 541,909 recorded lines remain in the source snapshot. The audit found 5,268 duplicate rows beyond the first, 135,080 missing customer IDs, 1,454 missing descriptions, 10,624 negative quantities, 1,336 negative-quantity rows without cancellation markers, 2,515 zero prices and two negative prices. December 2011 is partial. Full audit, row transformation hash, formulas and conventions are in [DATA.md](DATA.md) and `data_audit.json`.

Development uses December 2010 and January 2011. The evaluation blocks are February through September 2011, containing 293,303 original rows before project-specific filters. There are **eight nonoverlapping monthly blocks from one retailer**, sixteen constructed projects and two generation replicas. These are not sixteen independent organizations. Month blocks may still be serially dependent. Two projects within each block share records and are averaged together with their replicas for inference.

The data are recorded transactions. Briefs, scopes, roles, changes and disturbances are authored. Tool plans and messages are generated by Qwen on the GPU. Query execution, plotting arithmetic, validation and scoring are deterministic. There are no participants, measured attention costs, actual business savings or empirically established revenue-recognition rules. Recorded quantity and line value are precisely defined reporting conventions, not profit.

## Protocol and competence

The analysis agent selects every query parameter; a constrained tool compiles executable SQL. The chart agent selects the actual analysis result, displayed prefix and unit. The reporting agent selects the chart and unit; tool arithmetic supplies numerical claims. An independently scoped appendix retains its original contract. Public checks verify parameters, actual execution, units, data dependencies and consumed instruction hashes. The evaluator independently aggregates real records in Python. It never selects packets or recipients.

Each continuation has two rounds and at most two calls per role. A failed or unchanged artifact remains unfinished. Peer notification can forward an immutable user packet only along registered dependencies. The external API validates scope exceptions and rejects peer authority and unsupported argument shapes. It is a local application trust boundary, not a network identity service.

Initial unrestricted SQL pilots failed basic filters. The development interface was narrowed to explicit tool parameters and exact tool arithmetic. Two small prompt repairs beyond the provisional two-revision plan were required because the model treated missing old outputs as reasons to block or keep. The failed and interrupted development runs are retained. All four final development originals, and all **32 frozen evaluation originals**, completed all four structured artifacts under complete current instructions. This demonstrates competence with the constrained tools, not unrestricted SQL synthesis.

The adaptation pilot still contained unsupported nested report envelopes. We failed to diagnose that pattern before the primary freeze. The subsequent parser audit and exploratory follow-up are essential to interpreting the result.

## Frozen primary study

Commit `8935400b` freezes the code, task list, model settings, checks, scope rules, limits and analysis before held-out generation. All methods receive the same authorized changes and permitted checks. Shared state inspects every role and repairs invalid work. Active broadcast sends the applicable correction to every agent and charges its model processing even when no change is needed. Targeted routing sends the same packet to changed-contract roles. Sparse routing starts at affected roots and allows model notification plus a bounded global fallback. A same-packet global control isolates presentation from routing. The zero-inference pipeline exposes the strength of ordinary parameter flow.

Every policy receives actual fresh continuations from its paired original checkpoint. No response from a different prompt substitutes for a counterfactual generation. Execution order rotates. The model and decoding settings stay fixed. All planned primary and secondary runs completed.

{table(a['primary'])}

Each primary method has 32 project replicas, or 128 required structured artifacts. The table counts only adaptation calls; the **128 calls preparing the 32 common originals** are charged separately. The four LLM methods used **449 continuation calls**. No numerical artifact was incorrectly accepted. Eighteen leaf reports remained unfinished across the four methods. Unsupported schemas and a missing interpreted unit dominate these failures, so they must not all be described as semantic coordination errors.

The prespecified targeted-minus-broadcast mean call difference is **-1.125 calls/project**, 95% paired monthly-block bootstrap interval **[-1.3125, -1.0000]**. This is 36 fewer calls overall, or 26.5%. The structured-completion difference is **+3.125 percentage points**, interval **[0, 9.375]**, with **1 block win, 7 ties and 0 losses**. The improvement over the full shared-state presentation is +43.75 points [31.25, 56.25], but the parser confound prevents attributing that large difference to routing.

The matched same-packet global control, on replica 0, completed 15/16 versus targeted's 16/16, with **50 calls each**. The source-identical decision rules and fresh-generation variation, not a supported algorithmic superiority claim, explain how sampled runs can differ.

Broadcast rewrote 35 contract-unaffected artifacts, including protected appendices and unchanged analysis tables in display-only cases. Targeted, sparse and global checking rewrote none in the ordinary condition. A rewrite can leave the numbers correct; it still changes artifact identity. Active broadcast's extra calls primarily charge processing of irrelevant notifications. Passive delivery followed by a global check is represented by the stronger global controls and avoids that charge.

## Parser audit and separately declared fresh follow-up

The static leaf-artifact audit recognized equivalent explicit envelopes in **{terminal['recognized']}/{terminal['unfinished_reports']}** unfinished reports. All sixteen recognized cases pass the same public checks and private numerical comparison after local normalization of that final report. This is an artifact diagnostic, not a replacement policy trajectory. Two remaining forms have conflicting fields or unsupported structures.

Commit `b9962231` declares the follow-up before new generation. It uses all sixteen already inspected projects at replica 0, five methods, unchanged prompts and checks, and the same saved originals. The normalizer accepts only recognized `tool/params` envelopes with explicit values, never obtains missing parameters from the contract or evaluator, and rejects conflicting representations. It does not relax numerical or scope checks. Every continuation is newly generated. This is **post hoc exploratory sensitivity**, not a fresh held-out sample.

{table(follow)}

The follow-up used **250 new calls**. Targeted-minus-broadcast remains -1.125 calls/project [-1.3125, -1.0000], with identical observed structured completion. Targeted-minus-same-packet-global is **zero for both completion and calls in every block**. The bootstrap interval is consequently [0,0] on these observed paired differences; it is not a noninferiority or population-equivalence proof. The one remaining full-state failure uses `parameters` instead of the declared accepted `params` envelope. It is retained. No third parser revision or extra sample was run.

A protocol audit goes further than a statistical tie. In this fixed, scope-complete graph, every initially invalid role is exactly a changed-contract role. Both targeted and same-packet global checking then use the same order and fallback. Their follow-up request sequences match in **{route['identical_request_sequences']}/16 projects**. They cannot demonstrate different recipient-selection value under these conditions. The additional repeated inspection in the global implementation is a small implementation redundancy, not a new asymptotic advantage.

## Mechanism, stress and failures

The separately frozen stress condition corrupts a protected appendix parameter and value in the same way for each method, on the first project of each month, replica 0. Structured project completions are **6/8 global state, 7/8 broadcast, 7/8 targeted, 7/8 sparse and 8/8 targeted without detailed issue feedback**. Calls are 38, 35, 35, 34 and 34 respectively. Targeted and sparse require two rounds because they restore the appendix during expansion; broadcast averages 1.375 rounds. Extra feedback does not establish a benefit here. Restoring this corrupted appendix is necessary even though its contract is unchanged, so these rewrites must not be called unnecessary repairs.

Eight fully authored mechanism cases (32 controlled runs, zero inference) cover shared and local changes, no change, delayed notifications, false acknowledgment, corrupted exceptions, correlated wrong definitions and irrelevant forwarding. The controller preserves unfinished work and rejects unsupported cycles. These cases test properties, not real-world prevalence. The ordinary real-data comparison was not created by injecting baseline-only faults.

Among {variation['repeated_request_groups']} repeated identical primary/secondary request-payload groups, {variation['groups_with_different_parsed_outputs']} vary in parsed output text. One varies in envelope shape and therefore in strict-parser acceptance. After recognizing equivalent envelopes, **{variation.get('groups_with_different_normalized_tool_choices',0)} group differs in normalized tool representation**: a different May request returns a tool-description string without arguments in one run, and explicit usable arguments in the other. Thus normalization removes the April envelope difference but not every consequential output failure. Neither pair shows two distinct valid numerical parameter selections. Identical seeds do not promise bitwise reproducibility. Different prompts produced by changed dependencies remain a separate phenomenon. Saved-output replay is deterministic.

A post hoc narrative audit found four accepted structured reports for `eval_06_0`, replica 0, describing stock codes as customers. The same error appears under all four policies. This does not invalidate the prespecified numerical score, but it rules out describing that score as complete free-text correctness. The prototype keeps this generated prose in the evidence view and renders checked quantities with explicit schema/contract labels in the normal report card.

## What is and is not new

[AIPOM](https://aclanthology.org/2025.emnlp-demos.7/) already supports user edits, agent-plan repair and downstream reruns. [InstructFlow](https://papers.nips.cc/paper_files/paper/2025/file/03cfff3eccb29aa15f76e9bcee3d1be7-Paper-Conference.pdf) already uses execution feedback for graph-guided correction. Blackboard systems, event-triggered communication and incremental build systems supply other close mechanisms. [LITERATURE.md](LITERATURE.md) records the inspected sections, current versions and code availability.

The implemented contribution is an explicit scoped execution protocol, a public/private checking boundary, and a controlled real-data application that exposes parser, routing and tool effects separately. It is **not** a demonstrated new routing algorithm, a stability theorem, a measured reduction in human workload or evidence that multiple LLM agents improve this standardized analysis over a pipeline. Generic flocking terms do not change that assessment.

## Demonstration and reproducibility

The local Decision desk shows the current requirement, protected scope, affected artifacts, actual SQL, chart values, numerical claims, unresolved work and recorded agent responses. A user can apply a saved change once or choose a new supported country/metric/inclusion change through the deterministic pipeline. Historical and interface-repair traces are labeled separately. Source provenance, lookup fields and hashes remain expandable.

```bash
python3 -m research.coordination_injections.reproduce --download --output /tmp/coordination-replay
python3 -m research.coordination_injections.prototype.server --port 9033
bash paper/coordination_injections/build.sh
```

Open http://127.0.0.1:9033 for the demonstration. Full instructions are in [README.md](README.md). The standalone illustrated draft is `paper/coordination_injections/main.pdf`. Numerical figures have PDF/SVG/PNG exports under `artifacts/coordination_injections/figures/`, with captions stating their evidence types. Favorable and tied traces follow the frozen first-ID rule. No targeted-versus-broadcast unfavorable replica-0 example qualifies; that absence is reported rather than choosing a misleading substitute. The targeted replica-1 failure and the unfavorable stress outcome remain in the tables and raw evidence.

**Replay:** 248 original/pipeline/secondary traces reconstruct 803 model requests. Another 80 parser-follow-up traces reconstruct 250 requests. The final development version replays 20 traces and 72 requests. Older failed development requests and partial outcomes are retained rather than reinterpreted with the new parser. Focused protocol and normalization checks plus 65 relevant historical regressions pass. Scripted browser checks are software demonstrations, not participant observations. Build and clean-checkout verification records provide the final inspection results.

## Resource accounting and limitations

The stage started **2026-09-12 01:49:39 UTC**, with a **04:49:39 deadline** and **04:04:39 inference cutoff**. The original 36-hour window had already expired; its timestamps and historical commands remain unchanged. Stage and cumulative wall time, including inter-session gaps, are recorded in `resource_ledger.json`.

Inference totals are final: **{ledger['scheduled_calls']:,} scheduled calls, {ledger['attempts']:,} attempt intents, 1,314 returned successful responses, zero transport retries and zero returned HTTP failures**. Two development requests were interrupted: one before a generation intent, and one after an intent whose response was not retained. The latter is charged as an attempt with unknown tokens. Known usage is **{ledger['prompt_tokens']:,} prompt and {ledger['completion_tokens']:,} completion tokens**, {ledger['total_tokens']:,} total; at most one 2,048-token context worth of usage is unobserved. Returned generation latency sums to **{ledger['summed_returned_attempt_latency_seconds']:.2f} seconds**, not human response time or GPU billing duration. The main frozen study uses 803 calls; the parser follow-up uses 250; development accounts for the remainder.

At the report accounting checkpoint ({ledger['checkpoint_utc']}), stage wall time is {ledger['session_elapsed_seconds']/3600:.3f} hours. Cumulative wall time from the original start is {ledger['cumulative_wall_seconds']/3600:.3f} hours, including inter-session gaps, or {ledger['over_original_36h_seconds']/3600:.3f} hours beyond the historical 36-hour target. Cumulative accounting is {ledger['cumulative']['scheduled_calls']:,} scheduled calls and {ledger['cumulative']['attempts']:,} attempt intents. The final closing ledger records any later verification and commit overhead.

The existing RTX 6000 Ada server and cached pinned model were reused. Actual runtime is Python 3.11.13, PyTorch 2.8.0+cu128, CUDA runtime 12.8, Transformers 4.55.2 and vLLM 0.10.2. BF16 support and GPU engine allocation were checked. All generation used this GPU with zero CPU offload. Local orchestration uses Python 3.8.10. No paid resource was provisioned, no model was retrained and no participant or maintainer was contacted. Pod price and billed allocation are unavailable. Temporary local workers are stopped at completion; the existing model server is preserved.

The limited task space, explicit scope registration, single retailer, dependent month blocks, small paired sample, shared model across roles and unchecked prose constrain generalization. The data do not establish observed user workloads, repair benefit, accounting profit or semantic correctness of arbitrary instructions. The parser follow-up is exploratory and must remain separate from the frozen comparison.

## Claim-evidence map and recommendation

| Claim | Exact evidence | Limit |
|---|---|---|
| One change updates connected artifacts while preserving the appendix | `evaluation/frozen/eval_02_0_r0_targeted.json`, paired initial, interface screenshots | Constructed scope and workflow on recorded data |
| Targeted uses fewer calls than active broadcast in this matrix | `analysis/comparisons.json`, `analysis/episodes.csv` | Notification processing cost, not measured user effort |
| The initial global-state disadvantage is parser-sensitive | `analysis/terminal_envelope_audit.json`, `parser_followup/rows.json` | Follow-up uses inspected cases; original results retained |
| Targeted adds no distinct routing decision over same-packet global checking here | METHOD proof and `parser_followup/analysis/routing_audit.json` | Requires valid originals and complete registered dependencies |
| Numerical consistency does not establish narrative correctness | `analysis/failure_diagnostics.json` | Post hoc, incomplete prose audit |
| The standardized task does not establish value from LLM agents over a pipeline | All 32 pipeline traces, zero calls | Open-ended analytics was not tested |
| Replays preserve failures and budgets | Replay JSON, raw attempts, tests and resource ledger | Unknown response for one interrupted development attempt |

**Recommendation:** keep the practical scoped tool-and-state implementation, simplify to normalized global checking or the parameterized pipeline for this application, and do not make recipient routing the paper's central contribution. The next useful experiment is schema- and provenance-linked verification of generated narrative claims on new analytics tasks. The observed stock-code/customer confusion is a concrete unsolved problem; another queue or routing variation is not justified by this study.
'''
 (ROOT/'research/coordination_injections/REPORT.md').write_text(report)
 paper=ROOT/'paper/coordination_injections';bs=chr(92)
 def tex_table(rs):
  lines=[bs+'begin{center}',bs+'begin{tabular}{lrrrr}',bs+'toprule','Method & Complete & Unfinished & Calls & Tokens '+bs*2,bs+'midrule']
  for r in rs:lines.append(NAMES[r['method']]+' & '+str(r['project_correct_total'])+'/'+str(r['runs'])+' & '+str(r['unfinished_total'])+' & '+str(r['calls_total'])+' & '+format(r['tokens_total'],',')+' '+bs*2)
  return '\n'.join(lines+[bs+'bottomrule',bs+'end{tabular}',bs+'end{center}'])
 (paper/'abstract.tex').write_text(bs+'''begin{abstract}
We implement a protocol for adapting connected analytics artifacts after a scoped user change. It routes authorized corrections, executes proposed tools and checks actual uptake while preserving exceptions. A controlled study uses recorded UCI Online Retail transactions, sixteen constructed projects on eight monthly blocks, two generation replicas and fresh policy-specific GPU continuations. The frozen strict-parser study gives targeted delivery 31/32 complete structured projects in 100 calls, versus broadcast's 30/32 in 136. However, tool-envelope incompatibility confounds the larger apparent advantage over shared state. A separately declared exploratory follow-up accepts equivalent explicit envelopes and generates 250 fresh model responses in 80 continuations on inspected cases. Targeted and same-packet global checking each complete 16/16 projects in 46 calls, with identical request sequences. A deterministic pipeline completes all standardized contracts without model calls. The evidence supports scoped executable state management and exposes a parser confound, but does not establish a distinctive routing advance or reduced human workload. Generated prose can remain wrong despite correct numerical artifacts.
'''+bs+'end{abstract}\n')
 results='The 32 common originals all complete the four structured contracts. The frozen primary study gives the following results. Accepted numerical errors are zero for every method.\n'+tex_table(a['primary'])+'\nTargeted minus broadcast is -1.125 calls per project, with paired 95'+bs+'% bootstrap interval [-1.3125, -1.0000]. Structured completion differs by +3.125 percentage points [0, 9.375], with one block win and seven ties. The large +43.75-point contrast with the original full shared-state presentation is parser-sensitive and cannot be attributed to recipient selection. Sixteen of eighteen unfinished leaf reports become locally valid when equivalent explicit tool envelopes are recognized. This diagnostic does not replace the saved trajectories.\n\nThe separately declared parser follow-up uses the same sixteen inspected projects at replica 0 and actual new continuations. It is exploratory, not a new held-out sample.\n'+tex_table(follow)+'\nTargeted and same-packet global checking have identical request sequences on all sixteen pairs. Their observed paired completion and call differences are zero in every block. The degenerate paired bootstrap interval [0,0] is not a population-equivalence claim. Active broadcast processes unaffected notifications and uses eighteen more calls. The remaining full-state failure uses an unsupported '+bs+'texttt{parameters} envelope. No additional parser tuning or sample expansion follows.\n'
 (paper/'results.tex').write_text(results)
 (paper/'discussion.tex').write_text('The recipient-selection comparison has a structural limit. For valid original artifacts in this scope-complete graph, changed-contract roles are exactly the roles invalidated by the global check. Both methods then use the same topological order, packet and fallback. The compatible-parser audit confirms identical request sequences, so sampled differences cannot establish a distinctive routing algorithm. A redundant extra inspection in the global implementation is not a fundamental complexity benefit.\n\nIn the eight-case exception-corruption stress, completions are 6/8 for global state, 7/8 for broadcast, targeted and sparse, and 8/8 without detailed issue feedback. Targeted and sparse use two rounds; broadcast averages 1.375. This unfavorable control does not support a benefit from more corrective detail. Ordinary-condition broadcast rewrites 35 unaffected artifacts, whereas targeted, sparse and global checking rewrite none. Restoration of a deliberately corrupted appendix is necessary and is not included in that interpretation.\n\nThe primary evidence contains 152 groups of repeated identical request payloads. Eleven vary in parsed text and one varies in tool-envelope shape. The April pair has equal normalized tool parameters but different strict-parser acceptance. A May pair instead returns missing arguments versus an explicit usable tool envelope, so one normalized representation still differs. Seeds therefore do not promise bitwise reproduction. In addition, four accepted structured reports for the same project call stock codes customers. The numerical guard does not validate all prose. This directly limits any claim of full report correctness.\n\nThe real transactions ground the computations, not the authored workflow or user behavior. Scope and dependencies are registered explicitly. The parameterized pipeline is perfect without LLM calls. We therefore establish a useful execution boundary and an inspectable application, rather than a demonstrated need for multiple LLM agents or measured human attention savings.\n')
 (paper/'conclusion.tex').write_text(f'Known stage inference comprises {ledger["scheduled_calls"]:,} scheduled requests and {ledger["attempts"]:,} attempt intents, with 874,657 prompt and 112,851 completion tokens. One interrupted development attempt has unknown returned-token usage; another scheduled request never records a generation intent. The 803 frozen-study calls and 250 exploratory follow-up calls all return successfully. Historical clocks remain intact and no paid resource is provisioned. Final wall-time and shutdown records are in the resource ledger.\n\nFor these contracts, the supported choice is the parameterized pipeline or normalized global check. Targeted routing saves active-broadcast notification processing but adds no distinct allocation decision over the matched global control. A useful next investigation is provenance-linked verification of generated narrative claims on new analytical tasks. The observed entity-type error remains unsolved by agreement, version tracking and numerical checks.\n')
 examples=read(ART/'analysis/examples.json');parts=[]
 for label in ['favorable']:
  if label in examples:
   parts.append(bs+'begin{figure}[H]'+bs+'centering'+bs+'includegraphics[width=.88'+bs+'linewidth]{timeline_'+label+'.pdf}'+bs+'caption{'+label.capitalize()+' strict-parser example selected by the frozen first-ID rule. I denotes consumed contract version and A artifact revision. Green means public checks pass; orange means unfinished. These are recorded GPU/tool events, not human review durations. A tied example is saved separately. No unfavorable replica-0 case qualifies; replica-1 and stress failures remain reported.}'+bs+'end{figure}')
 (paper/'timeline_figures.tex').write_text('\n'.join(parts)+'\n')
 print('Report and manuscript text generated')
if __name__=='__main__':build()
