'use strict';
let state,shown=new Map(),currentShown=0,activeSeenKey='';const $=id=>document.getElementById(id);
const names={no_review:'No review',fifo:'Chronological queue',edf:'Earliest deadline',greedy:'Expected-benefit greedy',density:'Benefit / effort',fixed_window:'Fixed-window grouping',unguarded:'Unguarded sessions',sticky_edf:'Sticky EDF',allocation:'Capacity allocation',guarded:'Guarded sessions'};
const labels={normal:'Normal',outdoor_damper:'Outdoor damper',heating_valve:'Heating valve',cooling_valve:'Cooling valve',abstain:'Abstain / unresolved',invalid:'Invalid proposal'};
const channels={sat:'Supply air',outdoor:'Outdoor air',mixed:'Mixed air',return:'Return air',heat_sp:'Heating setpoint',cool_sp:'Cooling setpoint',fan:'Fan command',damper:'Damper command',cool_valve:'Cooling command',heat_valve:'Heating command'};
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x}
async function action(payload,render=true){let res=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let x=await res.json();if(!res.ok){$('error').hidden=false;$('error').textContent=x.error;return null}$('error').hidden=true;if(render){state=x;draw()}return x}
function log(kind,extra={}){action({action:'interaction',kind,...extra},false)}
function selection(){return Array.from(document.querySelectorAll('.select-card:checked')).map(x=>x.value)}
function draw(){
 $('policy').replaceChildren(...state.policies.map(p=>{const o=el('option',names[p]);o.value=p;o.selected=p===state.policy;return o}));$('reviewer').value=state.reviewer;$('bundle').value=state.bundle;$('load').value=state.load;
 const open=state.requests.filter(r=>['pending','deferred'].includes(r.status)).length,expired=state.requests.filter(r=>r.status==='expired').length;
 $('metrics').replaceChildren(...[[state.tick.toFixed(2),'Abstract replay time'],[state.used.toFixed(2)+' / '+state.budget,'Modeled active-time budget'],[open,'Pending or postponed'],[expired,'Expired, still visible']].map(([v,t])=>{let d=el('div',undefined,'metric');d.append(el('strong',String(v)),el('span',t));return d}));
 $('bound').textContent='Up to 3 separate decisions';$('reason').textContent=state.active.length?'Active session · '+state.active.length+' decisions remain':state.information.reason;
 let cert=state.information.certificate||{};let text=cert.valid?'Current public timing model preserves '+cert.protected.length+' feasible EDF opportunities. ':'No deadline-preservation certificate for this selection. ';
 text+='This does not guarantee human speed, future arrivals or correct answers.';const slack=Object.entries(cert.slack||{});if(slack.length)text+=' Outside-session slack: '+slack.map(([k,v])=>k+' '+v.toFixed(2)).join('; ')+'.';$('certificate').textContent=text;$('certificate').className=cert.valid?'':'warning';
 const pending=state.requests.filter(r=>r.status==='pending');const chosen=state.active.length?state.active:state.recommendation;
 pending.sort((a,b)=>(chosen.includes(a.request_id)?0:1)-(chosen.includes(b.request_id)?0:1)||a.deadline-b.deadline||a.request_id.localeCompare(b.request_id));
 $('cards').replaceChildren();if(!pending.length)$('cards').append(el('p','No decisions currently available. Deferred and expired requests remain in the queue.','helper'));
 for(const r of pending){
  let key=r.request_id;if(!shown.has(key))shown.set(key,performance.now());let current=state.active[0]===key;
  let card=el('article',undefined,'card'+(current?' current':''));card.dataset.id=key;let head=el('div',undefined,'card-head');let lab=el('label');let check=el('input');check.type='checkbox';check.className='select-card';check.value=key;check.checked=chosen.includes(key);check.disabled=state.active.length>0;lab.append(check,document.createTextNode(key+' · '+r.context));head.append(lab,el('span','Cutoff '+r.deadline.toFixed(2),'tag'));card.append(head);
  let proposal=el('div',labels[r.proposal]||r.proposal,'proposal');proposal.prepend(el('small','Agent proposal · '+r.evidence.window_start+'–'+r.evidence.window_end+' · '+r.evidence.equipment_mode));card.append(proposal);
  let signals=el('div',undefined,'signals');for(const k of ['sat','mixed','heat_valve']){let v=r.evidence.readings[k];let d=el('div',channels[k]+' mean');d.append(el('strong',v[0].toFixed(2)+(k==='heat_valve'?' fraction':' °F')));signals.append(d)}card.append(signals);
  let details=el('details');details.append(el('summary','Inspect the same source statistics'));let table=el('table');let tr=el('tr');for(const h of ['Signal','Mean','Min','Max','End − start'])tr.append(el('th',h));table.append(tr);for(const [k,v] of Object.entries(r.evidence.readings)){let row=el('tr');row.append(el('td',channels[k]||k));v.forEach(n=>row.append(el('td',Number(n).toFixed(2))));table.append(row)}details.append(el('p',r.evidence.units+'; 60 measured one-minute samples. No annotation is shown.'),table);details.addEventListener('toggle',()=>log('source_details',{request_id:key,expanded:details.open}));card.append(details);
  card.append(el('p','Estimated error risk '+r.risk.toFixed(3)+' · estimated review gain '+r.gain.toFixed(3)+' · consequence weight '+r.weight+'. Context reuse does not imply the same diagnosis.','helper'));
  if(current){let controls=el('div',undefined,'decision');let label=el('label','Your decision');let select=el('select');select.id='decision-'+key;for(const [v,t] of Object.entries(labels)){if(v==='invalid')continue;let o=el('option',t);o.value=v;o.selected=v===r.proposal;select.append(o)}label.append(select);let button=el('button','Record this decision','primary');button.id='submit-decision';button.onclick=()=>action({action:'decision',request_id:key,diagnosis:select.value,response_ms:performance.now()-currentShown,time_since_first_render_ms:performance.now()-shown.get(key)});controls.append(label,button);card.append(controls)}$('cards').append(card)
 }
 $('queue').replaceChildren();for(const r of state.requests){let d=el('div',undefined,'queue-item '+r.status);d.append(el('strong',r.request_id),el('span',r.status==='reviewed'?'Review recorded':r.status,'state'));d.append(el('span',r.context+' · cutoff '+r.deadline),el('span','Proposal: '+(labels[r.proposal]||r.proposal)));if(['pending','deferred'].includes(r.status)){let box=el('div',undefined,'defer');let input=el('input');input.type='number';input.step='.25';input.min=state.tick+.25;input.max=r.deadline-.25;input.value=Math.min(state.tick+2,r.deadline-.25);input.setAttribute('aria-label','Resume time for '+r.request_id);let b=el('button','Defer until');b.onclick=()=>action({action:'defer',request_id:r.request_id,until:Number(input.value)});box.append(b,input);if(r.deferred_until)box.append(el('span','Returns at '+r.deferred_until));d.append(box)}$('queue').append(d)}
 $('events').replaceChildren(...state.events.map(e=>el('li',e.tick.toFixed(2)+' · '+e.event+' '+(e.request_id||''))));$('start').disabled=state.active.length>0;$('end').disabled=!state.active.length;$('wait').disabled=state.active.length>0;
 const activeKey=state.session_serial+':'+(state.active[0]||'');if(activeKey!==activeSeenKey){currentShown=performance.now();activeSeenKey=activeKey}log('rendered',{request_ids:pending.map(r=>r.request_id),viewport_visible_ids:visibleCards(),active:state.active,recommendation:state.recommendation,context:state.context});
}
for(let b=0;b<6;b++){let o=el('option','Bundle '+b);o.value=b;$('bundle').append(o)}
$('policy').onchange=()=>action({action:'policy',policy:$('policy').value});$('start').onclick=()=>action({action:'start',ids:selection(),override:$('override').checked});$('end').onclick=()=>action({action:'end'});$('wait').onclick=()=>action({action:'wait'});$('replay').onclick=()=>action({action:'replay'});$('reset').onclick=()=>{shown.clear();action({action:'reset',policy:$('policy').value,bundle:Number($('bundle').value),reviewer:$('reviewer').value,load:$('load').value})};
fetch('/api/state').then(r=>r.json()).then(x=>{state=x;draw()});

function visibleCards(){return Array.from(document.querySelectorAll('.card')).filter(x=>{const r=x.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight}).map(x=>x.dataset.id)}
let scrollTimer;addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>log('viewport',{request_ids:visibleCards()}),120)},{passive:true});
